### ISSUE TITLE
server selection isn’t applied to the API client

### ISSUE THREAD

**Issue by Theodlz** [scalar/scalar#3132]
### What happens?

After selecting a server from the list of available servers at the top of the page (I'm deploying this with regular HTTP, embedding the API spec in it), when using the "Test Request" feature on any endpoint, it still shows the URL of the first server in the list, and on hover says "variable not found"

### What did you expect to happen?

It should ideally memorize the server selected at the top of the API spec and/or let me switch easily with something like a dropdown on click/hover of the server URL that already shows at the top of the Test Request dialog.

**Comment by amritk** [comment]
Yep known issue, we will have this one fixed tomorrow

**Comment by Theodlz** [comment]
Awesome, thanks!

**Comment by amritk** [comment]
Should have been fixed in https://github.com/scalar/scalar/pull/3138

release coming soon!

**Comment by Theodlz** [comment]
awesome! Great thanks

**Comment by Fylax** [comment]
Hello, I am using scalar server via CDN.

Seems like changing the server from the dropdown still doesn't produce any effect on the testing client.
Am I missing something?

**Comment by arushisingh1003** [comment]
Hi, I'm using the scalar-fastapi plugin to use scalar and the issue still persists. Any updates on this?
