### ISSUE TITLE
parameter example value are not retrieved

### ISSUE THREAD

**Issue by antlio** [scalar/scalar#3456]
### What happens?

It seems like the api client is not retrieving the parameter example, and yet not display it as a query parameter table value:

```yaml
  parameters:
  - example: example value
    in: query
    name: parameter_name
    required: true
    type: string
```

### What did you expect to happen?

<img width="828" alt="image" src="https://github.com/user-attachments/assets/4d588966-fa24-4d10-9dfe-a88deffa7b8c">

**Comment by amritk** [comment]
I think hans may have fixed this one already

**Comment by marclave** [comment]
@amritk @antlio confirmed fixed in latest release
![image](https://github.com/user-attachments/assets/64edc5be-30b9-4072-9338-9d41b1451427)

**Comment by kovapatrik** [comment]
I'm still experiencing this issue while using the HTML API Reference. I have some query params defined, for example:

```yaml
- name: user-id
  in: query
  required: true
  schema:
    type: string
    format: uuid
  example: 00000000-0000-0000-0000-000000000001
  x-go-name: UserIDQueryParam
  x-oapi-codegen-extra-tags:
    validate: "required,uuid"
```

In the API reference I can see this example in the curl command for example: 
![image](https://github.com/user-attachments/assets/ad7e3bc6-1f52-4a11-b38c-e553229ed6c1)

But it's not filled when opening the API client:
![image](https://github.com/user-attachments/assets/1d1142e6-995b-489a-a26e-8804bbf8952f)

**Comment by antlio** [comment]
hey @kovapatrik, sorry about that! will look into it!

**Comment by docHologram** [comment]
I still have issues with this using the .NET integration. 

```
imaging.MapGet("downloadBol", (long proNumber, [FromServices] DflImageService imaging) => imaging.DownloadBol(proNumber))
	.WithSummary("Download a BOL using a PRO#")
	.WithOpenApi(operation =>
	{
		var proNumberParameter = operation.Parameters.FirstOrDefault(p => p.Name == "proNumber");
		if (proNumberParameter != null)
		{
			proNumberParameter.Example = new OpenApiLong(62277285);
		}

		return operation;
	});
```

I should see 62277285 filled in for the query parameter but it's not there:

![Image](https://github.com/user-attachments/assets/22806aaa-5b71-41a1-a021-9893350300d3)

**Comment by antlio** [comment]
hey @docHologram sorry to hear - @xC0dex do you mind taking a look at this one?

**Comment by xC0dex** [comment]
Hey @docHologram, could you please share the generated OpenAPI document or check, if the example was added to it?

**Comment by xC0dex** [comment]
Hey @docHologram,

Just a quick note regarding the `WithOpenApi()` method: It currently has no effect when generating the OpenAPI document. This issue seems to be tracked [here](https://github.com/dotnet/aspnetcore/issues/59927). There is an [open PR](https://github.com/dotnet/aspnetcore/pull/60013) which will add another overload of the `WithOpenApi()` method, which you can probably use in the future.

**Comment by docHologram** [comment]
Thanks for your help @xC0dex. I decided to utilize the APIWeaver library for simple example query params. I also have a more complex endpoint whose query parameters have multiple examples. However, the first example for each is simply written and there is no way of accessing the other query param examples.

Will there be support in the future for a dropdown in the query params for all available examples, similar to what swashbuckle has done?
