### ISSUE TITLE
Dropdowns are broken in the settings tab

### ISSUE THREAD

**Issue by Polsulpicien** [scalar/scalar#3543]
### What happens?

You can't change the settings, clicking the dropdown menu isn't do anything:
![image](https://github.com/user-attachments/assets/52846010-cd23-404c-a39a-c56d675f5866)
The only way to do it right now is to tab into them

### What did you expect to happen?

Be able to change the settings

**Comment by leonlarsson** [comment]
Dropdowns in the UI of `@scalar/hono-api-reference` are also affected.
![2024-10-19_01-28-20](https://github.com/user-attachments/assets/665f4447-f915-4daf-a073-c5024d525d17)

**Comment by antlio** [comment]
hey @Polsulpicien @leonlarsson , sorry about that - thanks for the feedbacks though! will investigate asap and keep you updated here

**Comment by marclave** [comment]
@antlio @Polsulpicien @leonlarsson this is fixed in the latest release of both the CDN version & the Scalar API Client.

please update and you should see the fixes :)

**Comment by leonlarsson** [comment]
With `@scalar/hono-api-reference`, I still experience the issues. It uses the CDN link with no version tag, so I assume it should use the latest release

**Comment by marclave** [comment]
@leonlarsson i just cleared the cache, could you try hard refreshing and clearing your cache?

our latest cdn has this fixed

![image](https://github.com/user-attachments/assets/bda41e17-a91c-4c01-9b5a-3ebbc8f04ba5)

if this isnt fixed on your end i will take another look tomorrow

**Comment by leonlarsson** [comment]
No luck. Importing my OpenAPI .json into https://docs.scalar.com/swagger-editor does make the dropdowns work, however.
The issue persists in the `platform` path param and `count` query param in https://api.the-finals-leaderboard.com/#tag/leaderboards/GET/v1/leaderboard/s2/{platform} though

**Comment by LeaFrock** [comment]
The issue remains for 1.25.46.
I hava a boolean value in the query params, and the dropdown is broken when the hot key `T` and `F` work.

**Comment by antlio** [comment]
thank you all for the feedbacks! working on a fix and will push today!

**Comment by leonlarsson** [comment]
Great, thank you :)

**Comment by GabrielOGabs** [comment]
@antlio I have updated my .net project to use Scalar.AspNetCore 1.2.18 and even so my dropdowns are still not working. I've cleared the cache and hard refreshed but still with the same problem and I can't test my endpoints

**Comment by leonlarsson** [comment]
> @antlio I have updated my .net project to use Scalar.AspNetCore 1.2.18 and even so my dropdowns are still not working. I've cleared the cache and hard refreshed but still with the same problem and I can't test my endpoints

I don't believe it's been released yet

**Comment by leonlarsson** [comment]
I can confirm that on https://cdn.jsdelivr.net/npm/@scalar/api-reference@1.25.47, the dropdowns now work as expected! But https://cdn.jsdelivr.net/npm/@scalar/api-reference still resolves to `1.25.46` by default

**Comment by marclave** [comment]
@leonlarsson i purged the cdn cache, can you check again? might just be a time thing 😭

**Comment by LeaFrock** [comment]
It's been fixed in 1.25.47.  👍 Thanks a lot!

**Comment by leonlarsson** [comment]
Same here! Thanks :)
