### ISSUE TITLE
Requests with multipart/form-data content-type are not sent with data using the .NET package

### ISSUE THREAD

**Issue by aliatfoxtons** [scalar/scalar#4366]
### What happens?

When I have a request that takes a file, Scalar UI does setup the UI correctly, however when sending the request it does not set the file in the payload.

The request it produces comes out like this, and the File field is not populated when reaching the ASP.NET Core controller:

```curl
curl https://localhost:7158/api/upload \
  --request POST \
  --header 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryByJejQc3ZJnxvtYY' \
  --data "{"MyFile.xlsx":{"type":"file","text":"BINARY","name":"MyFile.xlsx","size":17082,"mimeType":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}}"
```

![image](https://github.com/user-attachments/assets/df58033a-ccc6-460d-be43-cb2b91396b45)

I'm not sure why the `data` argument is being rendered as JSON, it should be binary content?

The File appears on the UI, but changing the field name (`Key`) to 'File' does not update the payload being sent.

### What did you expect to happen?

When I setup my request using `IFormFile` as the upload argument like the following:

```csharp
public class UploadRequestDto
{
    public IFormFile File { get; set; } = null!;
}
```

and my controller uses the `[FromBody]` attribute for the request:

```csharp
public async Task<IActionResult> UploadAsync([FromForm] UploadRequestDto dto, CancellationToken cancellationToken) { }
```

then when a request is sent from scalar, the File field should be populated.

Version of package Scalar.AspNetCore: 1.2.72

**Comment by aliatfoxtons** [comment]
It looks like the package is not rendering the OpenAPI spec with the `formData` and `type: file` fields:

```json
"/api/upload": {
      "post": {
        "tags": [],
        "summary": "Upload",
        "description": "Upload a CSV file",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "File": {
                    "$ref": "#/components/schemas/IFormFile"
                  }
                }
              }
            }
          },
          "required": true
        }
    }
  },
```

**Comment by mzand111** [comment]
I had the same issue in 1.2.72 ,.. and still having the issue in 1.2.75

**Comment by aliatfoxtons** [comment]
> [@aliatfoxtons](https://github.com/aliatfoxtons) , there was a problem in the api client that caused the key to not update when uploading a file, this should be fixed in a recent PR, could you check if that fixed your issue as well?

Thank you, the issue is resolved now

**Comment by JaneConan** [comment]
the same problem remains
2.9.0

<img width="2824" height="1690" alt="Image" src="https://github.com/user-attachments/assets/d8ae8e0a-37c9-4746-af74-bd82434cecd5" />

<img width="1730" height="958" alt="Image" src="https://github.com/user-attachments/assets/11c285b5-17e5-4d3d-bda7-a7b981e0fe80" />

<img width="1186" height="1074" alt="Image" src="https://github.com/user-attachments/assets/4aec3bb8-d95e-47d0-a8d0-b7ec56b96bd4" />

**Comment by dpozimski** [comment]
i have the same issue with:
		<PackageReference Include="Scalar.AspNetCore" Version="2.11.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />

i want to pass IFormFile to my POST endpoint, with swagger ui (.net 9) it was working without any issue

**Comment by dpozimski** [comment]
@RemcoGoy https://github.com/scalar/scalar/issues/4366#issuecomment-3566935651 🙏
