### ISSUE TITLE
Scalar generates requests wrong to endpoints with "multipart/form-data" body.

### ISSUE THREAD

**Issue by AntonovAnton** [scalar/scalar#4546]
### What happens?

Hello,

Maybe I'm wrong but how I understand I have correct openapi schema, version 3.0.1:

```
"requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "file": {
                    "type": "string",
                    "description": "File upload (supports application/zip and application/json)",
                    "format": "binary"
                  }
                }
              },
              "encoding": {
                "file": {
                  "contentType": "application/json, application/zip"
                }
              }
            }
          },
```

I get this as an example of client code:
```
curl https://test/api/files \
  --request POST \
  --header 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryDQNF3crTqKX7u4fM' \
  --data "{"file":""}"
```

Could you please fix it?

### What did you expect to happen?

I expect to get correct examples in the Scalar UI for endpoints with "multipart/form-data" body, example below:
```
curl --location 'https://test/api/files' \
  --request POST \
  --header 'Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryDQNF3crTqKX7u4fM' \
  --form 'file=@"file1.json"' \
  --form 'file=@"file2.json"'
```

### OpenAPI Document

https://sandbox.scalar.com/e/9RHkq

**Comment by AntonovAnton** [comment]
@hanspagel Hey! Do you have any plans to fix this?

**Comment by amritk** [comment]
Hey I think this one is fixed! Feel free to re-open if it is not!

**Comment by AdamPaslawski** [comment]
> Hey I think this one is fixed! Feel free to re-open if it is not!

Hey @amritk , I am still seeing this issue. @AntonovAnton are you able to confirm this fix?

**Comment by amritk** [comment]
sorry @AdamPaslawski we just need to do a release, wanna try again in 30 or so minutes? If its still broken after I can take another look

**Comment by AdamPaslawski** [comment]
> sorry @AdamPaslawski we just need to do a release, wanna try again in 30 or so minutes? If its still broken after I can take another look 
> 
> 

Hey , confirming the fix is working for me. Thanks!
