### ISSUE TITLE
Test Request doesn't preview a body for the response

### ISSUE THREAD

**Issue by Zylvian** [scalar/scalar#5060]
### What happens?

When doing a 'Test Request' through the Scalar API on a local endpoint `https://localhost:7186/scalar/v1#tag/Project/POST/ProjectEndpoint/MyEndpoint`, there is no preview of the return body, no matter the response. 

![Image](https://github.com/user-attachments/assets/fa9bfc7b-5355-4ff5-a288-550884385e53)

### What did you expect to happen?

I expect a preview of the returned application/json, pretty-printed.

This bug happens for all types of responses, including OK 200.

I have attempted to run it with "Disable Cache" in the browser, but to no avail.

### OpenAPI Document

https://sandbox.scalar.com/e/28wh4

**Comment by sharppaul** [comment]
I can confirm that there's an issue with the preview—my request returns different content, but the preview doesn't update.

![Image](https://github.com/user-attachments/assets/8b849462-9f68-4e2d-ae8a-54d770c1c464)

**Comment by Human-Glitch** [comment]
We are experiencing the same issue as @Zylvian. It seems to have been present since early v2 release, and is reproducible since early v2 releases. 

Our team was working on implementing Scalar into our internal enterprise .Net 8 application, but unfortunately, this issue was a blocker for us. If other teams see this behavior using our scalar page, we would get false reports that our application is not working.

**Comment by hanspagel** [comment]
Would you mind to try again? I think we fixed that issue a few weeks ago already. 👀

**Comment by Human-Glitch** [comment]
@hanspagel It's still present. I actually figured out why it happens, and why errors specifically causes it.

When inspecting the network tab on the dev console, it complains that it can't read empty MIME responses. Which was weird because we always return application/json for al responses error or not.

What I realized was that we did not explicitly return response header for Content-Type on error responses. This is because error handling middleware doesn't automatically assign Content-Type when returning a response for errors.

It seems the Scalar client defaults to treating responses as MIME strings for some reason if no Content-Type is present in the response.

Anyway, what fixed it for us was to always return Content-Type application/json on responses.

**Comment by amritk** [comment]
Hey I'm going to close this one as stale and we changed the client completely since then, feel free to re-open if its still an isusue
