### ISSUE TITLE
v2.5.5/v2.5.6: Port is not used anymore

### ISSUE THREAD

**Issue by GeraldLx** [scalar/scalar#6210]
### What happens?

I have a .NET 9 application which is running locally on port 5001.

The servers array is cleared in my bootstrap code:

```
    app.MapScalarApiReference(options =>
    {
      options.Servers = [];
    });
```

When I run the application with v2.5.3 or lower I get

Server: http://localhost:5001

Doing the same with v2.5.5 or v.2.5.6 results in:

Server: http://localhost

Needless to say that of course all calls fail cause of using the wrong address.

### What did you expect to happen?

Obviously the previous behavior:

Server: http://localhost:5001

**Comment by xC0dex** [comment]
Hey @GeraldLx,

Thanks for filling out an issue. We just released version `2.6.0` and fixed a similar bug with this release. Could you try out the latest version?

Thanks!

**Edit**:

I was able to reproduce this issue.

**Comment by GeraldLx** [comment]
Thanks for the quick reply.
Sadly with 2.6.0 the bug remains.

**Comment by vfofanov** [comment]
Hi! I stuck with the same issue on 2.6.0

**Comment by xC0dex** [comment]
It's fixed in the upcoming release!
