### ISSUE TITLE
Error "ResizeObserver loop completed with undelivered notifications" with @scalar/docusaurus

### ISSUE THREAD

**Issue by mvanmeerbeck** [scalar/scalar#7044]
### What happens?

When using:
- @scalar/docusaurus@0.7.18 on docusaurus@3.9.0
- an enum query param 

- go to https://ppjzmw-3000.csb.app/scalar#tag/planets/get/planets
- click Test requests on "Get all planets"
- on the query param "testenum", click "select value"
- it triggers "ResizeObserver loop completed with undelivered notifications."

`openapi.json` extract

```
    testenum:
      name: testenum
      description: Testing enum
      in: query
      required: false
      schema:
        type: string
        enum: [foo, bar]
```

<img width="1495" height="733" alt="Image" src="https://github.com/user-attachments/assets/fbe7f367-f941-40f9-8260-f164778a930f" />

### What did you expect to happen?

it should show the options of the enum in a select

### OpenAPI Document

https://codesandbox.io/p/devbox/pensive-tereshkova-ppjzmw?workspaceId=ws_DRSx3iYdPhpWrsc5cyBYD9

**Comment by amritk** [comment]
Tagging in @hwkr as it may be dropdown related

**Comment by hwkr** [comment]
Hi @mvanmeerbeck! I tried the link you provided but wasn't able to reproduce the issue, do you mind posting a video of the issue? Also could be browser related, I tested in Chrome.

There do seem to be some overflow issues though which I'll fix ASAP :)

Here's what I tried, let me know if I missed something:

https://github.com/user-attachments/assets/7fc4c767-943a-4612-8232-1e6df6740ce0

**Comment by mvanmeerbeck** [comment]
Sure, Chrome Version 141.0.7390.65 (Build officiel) (64 bits)
22.04.1-Ubuntu

Also tested with no extension

https://github.com/user-attachments/assets/cd94a7e7-c45f-4dff-b8ef-cfa97334487e

**Comment by amritk** [comment]
ah maybe its a linux thing because I see the error

**Comment by mvanmeerbeck** [comment]
it works fine on my android phone and macos

**Comment by mvanmeerbeck** [comment]
One of my colleague has the problem on his macos (chrome & brave) tho

**Comment by mderazon** [comment]
This also happens to me when using @scalar/docusaurus with Docusaurus 3.9.2.

## Details

- **Package**: @scalar/docusaurus v0.7.20
- **Docusaurus Version**: 3.9.2
- **Browser**: Latest Chrome
- **OS**: Windows / WSL2

## Trigger
Clicking on the example dropdown selector for response examples (e.g., 400 error response examples) triggers the ResizeObserver error:

> ResizeObserver loop completed with undelivered notifications.

## Context
This occurs specifically with endpoints that have multiple examples in response objects. For example, a PATCH endpoint with 7 different 400 error examples. Other endpoints with fewer examples seem to work fine without triggering the error (I am not sure the amount of examples are the culprit)

## Impact
Dropdown is not opening

## OpenAPI Spec
The OpenAPI specification validates successfully with Redocly CLI, so this appears to be purely a Scalar UI rendering issue, not a spec problem.

## OpenAPI Spec Snippet

The issue occurs with this structure (simplified example from our PATCH /users/{id} endpoint):

```yaml
responses:
  "400":
    description: "400"
    content:
      application/json:
        examples:
          "No fields provided":
            value:
              type: invalid_request_error
              message: "At least one field must be provided to update."
              param: body
          "Invalid first name":
            value:
              type: invalid_request_error
              message: "Invalid first name: ''"
              param: first_name
          "Invalid role name":
            value:
              type: invalid_request_error
              message: "Invalid role name: 'InvalidRole'"
              param: role_name
          "Account Owner role not allowed":
            value:
              type: invalid_request_error
              message: "The 'Account Owner' role cannot be assigned directly via the API."
              param: role_name
          "Invalid teams format":
            value:
              type: invalid_request_error
              message: "Must be an array of strings."
              param: teams
          "Invalid team IDs":
            value:
              type: invalid_request_error
              message: "Invalid team(s): 'TM-INVALID1', 'TM-INVALID2'"
              param: teams
          "Unsupported field":
            value:
              type: invalid_request_error
              message: "Unsupported field"
              param: "{param_name}"
        schema:
          $ref: "#/components/schemas/Error"
```


![Image](https://github.com/user-attachments/assets/d7bab842-de05-4c27-a48b-fe911a263e9b)

**Comment by hwkr** [comment]
Huh, so I still wasn't able to replicate on my Mac but I was able to on my Windows machine. Will investigate further

**Comment by hwkr** [comment]
Okay so we've just released `@scalar/api-reference@1.39.0` and `@scalar/docusaurus
 @0.7.21` which includes some changes I made to those dropdowns to deal with overflow issues and it seems it may have fixed the issue.

@mvanmeerbeck I updated `@scalar/docusaurus` in the Codesandbox you provided and on my Windows machine it's working.

Updated CodeSandbox: https://codesandbox.io/p/sandbox/objective-williamson-dpxxt4

Are you and @mderazon able to update to latest and see if that fixes it for you? I think that code sandbox also updated the versions for some of the React stuff too so you may need to update those dependencies as well.

**Comment by mderazon** [comment]
@hwkr thanks for the update.
I've updated the packages in my project but unfortunately it still happens.

> Huh, so I still wasn't able to replicate on my Mac but I was able to on my Windows machine. Will investigate further

It is weird as it is inconsistent for me as well. On my local machine it happens consistently (Windows running in WSL)
When I push the code and deploy it ([Azure Static Web App](https://azure.microsoft.com/en-us/products/app-service/static)) it doesn't reproduce there (was like that before the version update as well).

So I am not sure what's going on exactly

**Comment by hwkr** [comment]
@mderazon Can you try comparing the two code sandboxes and see if you have the issue there?

Original (yours): https://codesandbox.io/p/devbox/pensive-tereshkova-ppjzmw
Updated: https://codesandbox.io/p/sandbox/objective-williamson-dpxxt4

**Comment by mderazon** [comment]
@hwkr indeed in codesandbox iti s fixed for me in the updated version (reproduced in the original version)

**Comment by hwkr** [comment]
Hmmmm that suggests to me it's something with the packages, I think in the repro version I switched the package sources from yarn to npm do you know if that would make a difference?

**Comment by hwkr** [comment]
Closing for now :)
