### ISSUE TITLE
[@scalar/openapi-types] $ref is missing on OpenAPIV3_1.ReferenceObject

### ISSUE THREAD

**Issue by snebjorn** [scalar/scalar#7405]
### What happens?

$ref seems to be missing from `OpenAPIV3_1.ReferenceObject`

<img width="616" height="198" alt="Image" src="https://github.com/user-attachments/assets/87936fa7-fc68-48b8-82e6-12feaf177cbd" />

It's interesting that it's there on the OpenAPIV3 type
<img width="492" height="108" alt="Image" src="https://github.com/user-attachments/assets/e6ea43b7-ac28-45c0-ac09-806724a2ec18" />

```ts
import type { OpenAPIV3_1, OpenAPIV3 } from '@scalar/openapi-types'

const ref: OpenAPIV3_1.ReferenceObject = {}
ref.$ref // any

const ref3: OpenAPIV3.ReferenceObject = {}
ref3.$ref // string | undefined
```

### What did you expect to happen?

I was expecting `OpenAPIV3_1.ReferenceObject` to have a `$ref: string | undefined` property

**Comment by hanspagel** [comment]
Fixed in #8275

**Comment by snebjorn** [comment]
@hanspagel sorry, I'm still seeing the issue in `@scalar/openapi-types@0.6.1`

I believe it's `AnyOtherAttribute` that's causing issues. When I do this

```ts
type Modify<T, R> = Omit<T, keyof R> & R;
type ReferenceObject = {
  $ref: string;
};
type ReferenceObject2 = Modify<
  ReferenceObject,
  {
    summary?: string;
    description?: string;
  }
>;

const ref: ReferenceObject2 = {};
```
I'm getting the expected properties
<img width="545" height="123" alt="Image" src="https://github.com/user-attachments/assets/0e2301f3-9a54-436c-ae79-ba9b771a62a1" />

But when I add `AnyOtherAttribute`

```ts
type Modify<T, R> = Omit<T, keyof R> & R;
type AnyOtherAttribute = {
  [customExtension: `x-${string}`]: any;
  [key: string]: any;
};
type ReferenceObject = {
  $ref: string;
} & AnyOtherAttribute;
type ReferenceObject2 = Modify<
  ReferenceObject,
  {
    summary?: string;
    description?: string;
  }
>;

const ref: ReferenceObject2 = {};
```

<img width="541" height="97" alt="Image" src="https://github.com/user-attachments/assets/fd6015ae-b3de-4910-b110-551a73323689" />
